### ISSUE TITLE
Merge "cancel action" PR

### ISSUE THREAD

**Issue by jaredcat** [gareth-smyth/service.sleeptimer#2]
Could you please pull in this PR? Seems like a great addition  https://github.com/enen92/service.sleeptimer/pull/14

**Comment by gareth-smyth** [comment]
Hi sorry it took me a while to get back to you.  I'm not sure of the status of https://github.com/enen92/service.sleeptimer but I'm guessing this should go in there?

**Comment by jaredcat** [comment]
Yea that would be ideal but enen92 seems to have stopped supporting the plugin. I'm currently using your fork since it's updated to work the current version Kodi.
